spring:
  profiles: test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.23.212.211:3306/leaveword?characterEncoding=utf8&useSSL=false
    username: root
    password: 19961002withme